### ISSUE TITLE
Error with TBB CMake on OS X

### ISSUE THREAD

**Issue by izaid** [intel/parallelstl#16] opened 2018-07-07 22:14 UTC
Hello,

I've been using parallelstl for a few months, and it is really a fantastic library.

I've just upgraded to the latest release, which includes CMake support. But, when I add the parallelstl subdirectory in CMake, I get the following error:

```
CMake Error at /usr/local/lib/cmake/TBB/TBBConfig.cmake:77 (message):
  Missed required Intel TBB component: tbb
Call Stack (most recent call first):
  third_party/parallelstl-20180619/CMakeLists.txt:39 (find_package)


-- Configuring incomplete, errors occurred!
```

To be clear, I definitely have TBB installed. I'm on OS X and I installed it via brew. Its header files and libraries are setting in `/usr/local/include` and `/usr/local/lib` respectively. If I skip the parallelstl CMake and add things manually, everything is fine.

I was hoping there would be some variable somewhere, like `TBB_ROOT` or something, that I could set that would make the TBB CMake happy, but so far nothing has worked. Any thoughts?

Thanks!

**Comment by AlexVeprev** [comment] 2018-07-10 07:50
Hi @izaid,

Thank you for the detailed description!
I've reproduced the issue and found a root cause in incorrect TBBConfig.cmake installed with TBB package.
Looks like Homebrew generates this TBBConfig.cmake using scripts provided by TBB ([homebrew-core/Formula/tbb.rb:37](https://github.com/Homebrew/homebrew-core/blob/2ea319227df3080e5d8d93b4e5a8442835450a23/Formula/tbb.rb#L37)), but the TBB CMake scripts support configuring [packages provided by TBB team via GitHub](https://github.com/01org/tbb/releases) only. These packages have different structure from Homebrew packages.

The most evident to me ways to resolve it:
1. Improve TBB CMake config generators to support Homebrew structure. I can propose the implementation; it will be available when TBB with the improvement is released and Homebrew takes the release.
2. Write a CMake module finding pre-installed TBB (it's going to be done in scope of PR #13). This approach will work when Parallel STL delivers the module. Or you can write your own implementation for your project (I suppose, it'll be quite simple if you're going to use it with Homebrew TBB only, I can help if needed).

@henryiii, could you please take a look? Maybe you have something to add.

**Comment by rodgert** [comment] 2018-07-11 15:25
@AlexVeprev Erk, I don't currently have a means of testing OSX/Homebrew changes (my MBP is out for repair) but I'd be interested in a fix to this as well. If nobody beats me to it, I will attempt to fix it when I get my Mac back.

This is a bit of slippery slope though since now there's Brew for Linux, should that also be supported?

**Comment by henryiii** [comment] 2018-07-11 18:01
@AlexVeprev , quick historical perspective. The problem is that ParallelSTL now has its own CMake config, which expects a working TBB Config (by request of Intel). I warned about the broken TBBConfig in brew back then, and the solution was "fix the one in Brew", which is quite correct, but also does not seem to have been done.

**Comment by izaid** [comment] 2018-07-12 10:10
Just wanted to say thanks for looking into this. For now, I'm not going to use ParallelSTL's CMake files, but hopefully will be able to as soon as they work with brew.

**Comment by AlexVeprev** [comment] 2018-07-12 13:38
@rodgert, I think it would be better to have support for many popular package managers (including DNF mentioned in PR #13). But initially it is enough to have support for things required asap.

@henryiii, thank you for the explanation!

**Comment by rodgert** [comment] 2018-07-13 15:06
@AlexVeprev agreed. FWIW, it works fine with Fedora28 and DNF as is (that's my primary development platform).

**Comment by AlexVeprev** [comment] 2018-07-13 16:12
I've pushed [a PR simplifying FindTBB.cmake](https://github.com/rodgert/parallelstl/pull/1) into @rodgert repo in order to include it into PR #13 (or into a separate PR if there are objections).

This FindTBB.cmake works for me on Mac with TBB installed using Homebrew.
You are welcome for review.

**Comment by tbbdev** [comment] 2018-12-05 09:55
Hi @izaid,
In the release [20181204 ]( https://github.com/intel/parallelstl/tree/20181204) we added FindTBB CMake module as a Preview Feature. It is invoked from Parallel STL CMakeLists.txt.
Could you please check if this solves your issue?

**Comment by hjmjohnson** [comment] 2019-01-19 15:54
@tbbdev Fixes for this problem are https://github.com/01org/tbb/pull/119
and temporary changes are listed as a temporary homebrew patch at:
Homebrew/homebrew-core#36175

**Comment by tbbdev** [comment] 2019-07-05 10:59
The issue is fixed in Homebrew TBB formula: https://github.com/Homebrew/homebrew-core/pull/38844

**Closed by tbbdev** 2019-07-05 10:59 UTC
